CREATE TABLE pincodes (
    id SERIAL PRIMARY KEY,
    event_id VARCHAR(225) NOT NULL,
    email VARCHAR(225) NOT NULL,
    pincode VARCHAR(225) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)